name: NanoBSD

on:
  repository_dispatch:
    types:
      - build

  workflow_dispatch:
    inputs:
      NANO_CONFIG:
        description: Link to a NanoBSD config file
        required: false
        default: ""

jobs:
  nanobsd:
    name: Build a NanoBSD disk image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FreeBSD
        uses: actions/checkout@v4
        with:
          repository: freebsd/freebsd-src

      - name: Store parameters
        run: |
          echo "NANO_CONFIG=${{ github.event.inputs.NANO_CONFIG || github.event.client_payload.nano_config }}" >> $GITHUB_ENV

      - name: Build NanoBSD
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: '14.1'
          run: |
            cd $GITHUB_WORKSPACE/tools/tools/nanobsd
            if [ -z ${{ env.NANO_CONFIG }} ]; then
              sh nanobsd.sh
            else
              sh nanobsd.sh -c ${{ env.NANO_CONFIG }}
            fi
